#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 30

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 4

#define SERIAL_NUMBER "XWJ6M/NoWYod"
#define LAYER_STATE_16BIT

#define TAPPING_TERM 170
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
